# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=1.21.11
yarn_mappings=1.21.11+build.4
loader_version=0.18.4
loom_version=1.15.3
# Mod Properties
mod_version=0.0.1-SNAPSHOT
maven_group=sb.rocket
archives_base_name=giovanniclient
# Dependencies
# check this on https://modmuss50.me/fabric.html
# kotlin_version=1.13.8
fabric_api_version=0.141.3+1.21.11
# fabric_command_api_version=3.0.3+c779aa61e7
moulconfig_artifact=modern-1.21.11
moulconfig_version=4.3.0-beta
REI_version=21.11.814
