pluginManagement {
    repositories {
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        mavenCentral()
        gradlePluginPortal()
    }
}

includeBuild('libautoupdate-gc') {
    dependencySubstitution {
        substitute module('moe.nea:libautoupdate') using project(':')
    }
}

rootProject.name = 'giovanniclient'